import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <header className="p-4 border-b ">
                    <h1 className="font-bold text-xl">Next App</h1>
                </header>
                <div className="flex p-4">
                    <aside className="w-[250px] pr-4 mr-4 flex flex-col">
                        <a href="/">Home</a>
                        <a href="/search">Search</a>
                        <a href="/person/123">Person</a>
                    </aside>
                    <main className="p-4 flex-grow">{children}</main>
                </div>
            </body>
        </html>
    );
}
