import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Sidebar from "@/components/sidebar";
import { MagnifyingGlassIcon } from "@radix-ui/react-icons";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "./modeToggle/page";
import { Input } from "@/components/ui/input";
import { redirect } from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    async function search(formData: FormData) {
        "use server";

        redirect(`/search?q=${formData.get("q")}`);
    }
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div>
                        <header className="p-4 border-b flex flex-row justify-between">
                            <h1 className="font-bold text-xl flex items-center gap-2">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="24"
                                    height="24"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    strokeWidth="2"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    className="lucide lucide-clapperboard-icon lucide-clapperboard"
                                >
                                    <path d="M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3Z" />
                                    <path d="m6.2 5.3 3.1 3.9" />
                                    <path d="m12.4 3.4 3.1 4" />
                                    <path d="M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" />
                                </svg>
                                Movie World
                            </h1>

                            <div className="flex gap-5">
                                <form className="flex gap-1" action={search}>
                                    <Input
                                        placeholder="Search movie"
                                        name="q"
                                    />
                                    <Button>
                                        <MagnifyingGlassIcon />
                                    </Button>
                                </form>

                                <ModeToggle />
                            </div>
                        </header>
                    </div>
                    <div className="flex p-4">
                        <Sidebar />

                        <main className="pl-4 flex-grow">{children}</main>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
